### PR TITLE
Dev user management

### PR DESCRIPTION
**Pull request by raphaelmonnard**
- Create user list with HTMX filter for superuser
- Add user subcription for superuser
- Implement user registration form

### CODE REVIEW

**Comment by niaou73** [comment]
Problem with migration if the pull request #85 isn't migrated.
[error.log](https://github.com/fablab-chaux-de-fonds/Interlab/files/7887470/error.log)

**Comment by niaou73** [comment]
project is called Interlab and not interfab as in README.md

**Comment by niaou73** [comment]
error with static files loading, the url of these resources is set with port 9091 which is not opened by docker.

**Comment by niaou73** [comment]
A csrf token is shown in query string when a user register to the newsletter. The POST method would be a better choice.

**Comment by niaou73** [comment]
Back button on edit profile page. The user may want to cancel the edition of its profile.

**Comment by raphaelmonnard** [comment]
- invitation issue: fixed in PR88 a8e0328da2f3f991f11806d2dcb64002fcc61519

**Comment by raphaelmonnard** [comment]
- no name during registration
- E-mail: activation échouée

**Pull request merged**
